#baseURL = "https://puzzlewolf.github.io/recipes/"
baseURL = "https://recipes.nora.pink/"
languageCode = "de-de"
title = "Noras Rezepte"
theme = "kiera"
canonifyurls = true
DefaultContentLanguage = "de-de"

[author]
name = "Nora Widdecke"
github = "puzzlewolf/recipes"
#gitlab = "puzzlewolf"

[frontmatter]
#date = [":git"]

[params]
tagline = "Meine Rezeptesammlung"
