baseURL = "http://example.org/"
languageCode = "en-us"
title = "Nora's recipes"
theme = "kiera"

enableGitInfo = true

[author]
name = "Nora Widdecke"
github = "puzzlewolf"
gitlab = "puzzlewolf"

[frontmatter]
#date = [":git"]

[params]
tagline = "My recipe collection"
