#baseURL = "https://puzzlewolf.github.io/recipes/"
baseURL = "https://recipes.nora.pink/"
languageCode = "de-de"
title = "Nora's recipes"
theme = "kiera"
canonifyurls = true
enableEmoji = true

enableGitInfo = true

[author]
name = "Nora Widdecke"
github = "puzzlewolf/recipes"
#gitlab = "puzzlewolf"

[frontmatter]
#date = [":git"]

[params]
tagline = "My recipe collection"
